### ISSUE TITLE
Peer To Peer Project Review - 27/11/2019

### ISSUE THREAD

**Issue by lekegitrepo** [SofiBretz/test_app#1]
## Enhancements

- Try to follow the Git/Github flow.
- Check the existent of an article(object) in the set_article method before applying any action on the article(object).

## Further Comments
> Reviewed with <3 by Team 35: The Deadpools

**Comment by SofiBretz** [comment]
### Summary of Changes: 

- Git flow updated.
- Check the existent of the article object in set_article.

Thank you Team! :)
